[package]
name = "nosh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix="0.25.0"
whoami="1.2.3"
dirs="4.0.0"

colorize="0.1.0"
